export const CalendarDescription = [
  "'For I know the plans I have for you,' declares the Lord, 'plans to prosper you and not to harm you, plans to give you a hope and a future.' - Jeremiah 29:11",
  "'I can do all things through Christ who strengthens me.' - Philippians 4:13",
  "'Don’t let anyone look down on you because you are young, but set an example for the believers in speech, in conduct, in love, in faith and in purity.' - 1 Timothy 4:12",
  "'He gives strength to the weary and increases the power of the weak. Even youths grow tired and weary, and young men stumble and fall; but those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.' - Isaiah 40:29-31",
  "'How can a young person stay on the path of purity? By living according to your word.' - Psalm 119:9",
  "'You are the light of the world. A town built on a hill cannot be hidden. Neither do people light a lamp and put it under a bowl. Instead, they put it on its stand, and it gives light to everyone in the house. In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.' - Matthew 5:14-16",
  "'Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God’s will is—his good, pleasing and perfect will.' - Romans 12:2",
  "'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.' - Proverbs 3:5-6",
  "'For God gave us a spirit not of fear but of power and love and self-control.' - 2 Timothy 1:7",
  "'Remember your Creator in the days of your youth, before the days of trouble come and the years approach when you will say, 'I find no pleasure in them.'' - Ecclesiastes 12:1",
  "'The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?' - Psalm 27:1",
  "'Cast all your anxiety on him because he cares for you.' - 1 Peter 5:7",
  "'Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.' - Joshua 1:9",
  "'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters, since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving.' - Colossians 3:23-24",
  "'Similarly, encourage the young men to be self-controlled. In everything set them an example by doing what is good. In your teaching show integrity, seriousness and soundness of speech that cannot be condemned.' - Titus 2:6-8",
  "'Above all else, guard your heart, for everything you do flows from it.' - Proverbs 4:23",
  "'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.' - Romans 8:28",
  "'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us, fixing our eyes on Jesus, the pioneer and perfecter of faith.' - Hebrews 12:1-2",
  "'But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.' Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me.' - 2 Corinthians 12:9",
  "'There is surely a future hope for you, and your hope will not be cut off.' - Proverbs 23:18",
]